postgres:
    image: gaocegege/postgres:9
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

writer:
    image: gaocegege/hackys-writer:latest
    links:
    - "postgres:postgres"
    ports:
    - "8088:8088"

reader:
    image: gaocegege/hackys-reader:latest
    links:
    - "postgres:postgres"
    ports:
    - "8089:8089"
